server:
  port: 8090
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  rabbitmq:
    host: localhost
    port: 5672
    username: mustafa
    password: 123
  datasource:
    url: jdbc:postgresql://localhost:5432/java5AuthDb
    password: root
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secretKey: ${secretkey}
  issuer: ${issuer}
  audience: ${audience}

rabbitmq:
  exchange-auth: auth-exchange
  registerkey: register-key
  queueRegister: register-queue
  queueEmail: email-queue
  emailKey: email-key


